image: frolvlad/alpine-glibc

before_script:
  - apk update && apk --no-cache add g++ gcc libgcc libstdc++ linux-headers make python3 curl tar nodejs npm git

  # Cache node modules - speeds up future builds
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules

# Define the stages
stages:
  - setup
  - test
  - build
  - deploy

# Define the process for each stage

# Define the process for setup stage
setup:
  stage: setup
  tags:
    - ohtu-build-2
  script:
    - npm ci

# Define the process for test stage
test:
  stage: test
  tags:
    - ohtu-build-2
  script:
    - npm test
  coverage: /All files\s*\|\s*([\d\.]+)/

build_dev:
  stage: build
  tags:
    - ohtu-build-2
  only:
    - master
  script:
    - yes | cp -f -v .env.development .env.production || true
    - npm run build
  artifacts:
    name: orgrek-build
    paths:
      - build

build_test:
  stage: build
  tags:
    - ohtu-build-2
  only:
    - test
  script:
    - yes | cp -f -v .env.test .env.production || true
    - npm run build
  artifacts:
    name: orgrek-build
    paths:
      - build

build_prod:
  stage: build
  tags:
    - ohtu-build-2
  only:
    - prod
  script:
    - npm run build
  artifacts:
    name: orgrek-build
    paths:
      - build

# Define the process for deploy stage to development environment
deploy_dev:
  stage: deploy
  tags:
    - ohtu-build-2
  environment:
    name: development
  only:
    - master
  script:
    - mv nginx_dev.conf nginx.conf
    - curl -fsSLO --compressed "https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/openshift-client-linux.tar.gz";
    - tar xvzf openshift-client-linux.tar.gz -C /usr/local/bin
    # before any action, I connect to the OpenShift server with the appropriate credentials
    # this parameter: `--insecure-skip-tls-verify` is important because we use a certificate signed by an unknown authority
    - oc login https://$OPENSHIFT_ADDR_TEST:$OPENSHIFT_PORT --token=$OPENSHIFT_TOKEN_TEST --insecure-skip-tls-verify
    - oc project organisaatiorekisteri
    - oc set env dc/organisaatiorekisteri-frontend-dev REACT_APP_GIT_BRANCH=$(echo ${CI_COMMIT_BRANCH})
    - oc set env dc/organisaatiorekisteri-frontend-dev REACT_APP_GIT_HASH=$(git rev-parse --short=7 HEAD)
    - oc start-build organisaatiorekisteri-frontend-dev --from-dir=. --follow

deploy_test:
  stage: deploy
  tags:
    - ohtu-build-2
  environment:
    name: test
  only:
    - test
  script:
    - mv nginx_test.conf nginx.conf
    - curl -fsSLO --compressed "https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/openshift-client-linux.tar.gz";
    - tar xvzf openshift-client-linux.tar.gz -C /usr/local/bin
    # before any action, I connect to the OpenShift server with the appropriate credentials
    # this parameter: `--insecure-skip-tls-verify` is important because we use a certificate signed by an unknown authority
    - oc login https://$OPENSHIFT_ADDR_TEST:$OPENSHIFT_PORT --token=$OPENSHIFT_TOKEN_TEST --insecure-skip-tls-verify
    - oc project organisaatiorekisteri
    - oc start-build organisaatiorekisteri-frontend-test --from-dir=. --follow

deploy_prod:
  stage: deploy
  tags:
    - ohtu-build-2
  environment:
    name: prod
  only:
    - prod
  script:
    - mv nginx_prod.conf nginx.conf
    - curl -fsSLO --compressed "https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/openshift-client-linux.tar.gz";
    - tar xvzf openshift-client-linux.tar.gz -C /usr/local/bin
    # before any action, I connect to the OpenShift server with the appropriate credentials
    # this parameter: `--insecure-skip-tls-verify` is important because we use a certificate signed by an unknown authority
    - oc login https://$OPENSHIFT_ADDR_PROD:$OPENSHIFT_PORT --token=$OPENSHIFT_TOKEN_PROD --insecure-skip-tls-verify
    - oc project organisaatiorekisteri
    - oc start-build organisaatiorekisteri-frontend-prod --from-dir=. --follow
