image: quay.io/tike/alpine-oc-node

variables:
  npm_config_cache: '$CI_PROJECT_DIR/.npm'

# Define a hidden job to be used with extends
# Better than default to avoid activating cache for all jobs
.dependencies_cache:
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - .npm
    policy: pull

# Define the stages
stages:
  - setup
  - test
  - audit_scan
  - build
  - deploy

# Define the process for setup stage
setup:
  stage: setup
  script:
    - curl -X GET https://gw-api-test.it.helsinki.fi/organisation/info/v1/texts -H accept:application/json -H X-Api-Key:$TEST_API_GW_KEY -o texts.json
    - >
      CYPRESS_CACHE_FOLDER='.cache/Cypress'
      PLAYWRIGHT_BROWSERS_PATH=.cache/ms-playwright
      npm ci
  tags:
    - ohtu-build-3
  extends: .dependencies_cache
  cache:
    policy: pull-push
  artifacts:
    expire_in: 1h
    paths:
      - node_modules
      - texts.json

# Define the process for test stage
test:
  stage: test
  tags:
    - ohtu-build-3
  script:
    - npm test
  coverage: /All files\s*\|\s*([\d\.]+)/

storybook_test:
  stage: test
  image: mcr.microsoft.com/playwright:v1.31.2-focal
  tags:
    - ohtu-build-3
  script:
    - npm run storybook:build
    - npm run storybook:test:ci
  coverage: /All files\s*\|\s*([\d\.]+)/

build_dev:
  stage: build
  tags:
    - ohtu-build-3
  only:
    - master
  script:
    - yes | cp -f -v .env.development .env.production || true
    - CI=false npm run build
  artifacts:
    name: orgrek-build
    paths:
      - build

build_organisation_dev:
  stage: build
  tags:
    - ohtu-build-3
  only:
    - organisation-dev
  script:
    - yes | cp -f -v .env.organisation-development .env.production || true
    - CI=false npm run build
  artifacts:
    name: orgrek-build
    paths:
      - build

build_test:
  stage: build
  tags:
    - ohtu-build-3
  only:
    - test
  script:
    - yes | cp -f -v .env.test .env.production || true
    - CI=false npm run build
  artifacts:
    name: orgrek-build
    paths:
      - build

build_prod:
  stage: build
  tags:
    - ohtu-build-3
  only:
    - prod
  script:
    - CI=false npm run build
  artifacts:
    name: orgrek-build
    paths:
      - build

# Define the process for deploy stage to development environment
deploy_dev:
  stage: deploy
  tags:
    - ohtu-build-3
  environment:
    name: development
  only:
    - master
  except:
    # Skip deploy when scheduled npm audit and outdated scans are executed.
    - schedules
  script:
    # set home path for openshift 1001 user
    - export HOME=/home/1001
    - mv nginx_dev.conf nginx.conf
    # before any action, I connect to the OpenShift server with the appropriate credentials
    - oc login https://$OPENSHIFT_ADDR_TEST:$OPENSHIFT_PORT --token=$OPENSHIFT_TOKEN_TEST
    - oc project organisaatiorekisteri
    - oc set env dc/organisaatiorekisteri-frontend-dev REACT_APP_GIT_HASH=$(git rev-parse --short=7 HEAD)
    - oc set env dc/organisaatiorekisteri-frontend-dev TZ="Europe/Helsinki"
    - oc start-build organisaatiorekisteri-frontend-dev --from-dir=. --follow
    - oc patch bc/organisaatiorekisteri-frontend-dev --patch '{"spec":{"successfulBuildsHistoryLimit":1}}'
    - oc patch bc/organisaatiorekisteri-frontend-dev --patch '{"spec":{"failedBuildsHistoryLimit":1}}'
    # set pod memory quota to 100 MB and limit to 500 MB
    - oc set resources dc/organisaatiorekisteri-frontend-dev --limits=memory=500Mi --requests=memory=100Mi

deploy_test:
  stage: deploy
  tags:
    - ohtu-build-3
  environment:
    name: test
  only:
    - test
  except:
    # Skip deploy when scheduled npm audit and outdated scans are executed.
    - schedules
  script:
    # set home path for openshift 1001 user
    - export HOME=/home/1001
    - mv nginx_test.conf nginx.conf
    # before any action, I connect to the OpenShift server with the appropriate credentials
    - oc login https://$OPENSHIFT_ADDR_TEST:$OPENSHIFT_PORT --token=$OPENSHIFT_TOKEN_TEST
    - oc project organisaatiorekisteri
    - oc set env dc/organisaatiorekisteri-frontend-test REACT_APP_GIT_HASH=$(git rev-parse --short=7 HEAD)
    - oc set env dc/organisaatiorekisteri-frontend-test TZ="Europe/Helsinki"
    - oc start-build organisaatiorekisteri-frontend-test --from-dir=. --follow
    - oc patch bc/organisaatiorekisteri-frontend-test --patch '{"spec":{"successfulBuildsHistoryLimit":1}}'
    - oc patch bc/organisaatiorekisteri-frontend-test --patch '{"spec":{"failedBuildsHistoryLimit":1}}'
    # set pod memory quota to 100 MB and limit to 500 MB
    - oc set resources dc/organisaatiorekisteri-frontend-test --limits=memory=500Mi --requests=memory=100Mi

deploy_prod:
  stage: deploy
  tags:
    - ohtu-build-3
  environment:
    name: prod
  only:
    - prod
  except:
    # Skip deploy when scheduled npm audit and outdated scans are executed.
    - schedules
  when: manual
  script:
    # set home path for openshift 1001 user
    - export HOME=/home/1001
    - mv nginx_prod.conf nginx.conf
    # before any action, I connect to the OpenShift server with the appropriate credentials
    - oc login https://$OPENSHIFT_ADDR_PROD:$OPENSHIFT_PORT --token=$OPENSHIFT_TOKEN_PROD
    - oc project organisaatiorekisteri
    - oc set env dc/organisaatiorekisteri-frontend-prod REACT_APP_GIT_HASH=$(git rev-parse --short=7 HEAD)
    - oc set env dc/organisaatiorekisteri-frontend-prod TZ="Europe/Helsinki"
    - oc start-build organisaatiorekisteri-frontend-prod --from-dir=. --follow
    - oc patch bc/organisaatiorekisteri-frontend-prod --patch '{"spec":{"successfulBuildsHistoryLimit":1}}'
    - oc patch bc/organisaatiorekisteri-frontend-prod --patch '{"spec":{"failedBuildsHistoryLimit":1}}'
    # set pod memory quota to 100 MB and limit to 500 MB
    - oc set resources dc/organisaatiorekisteri-frontend-prod --limits=memory=500Mi --requests=memory=100Mi

# Rules for the scheduled npm audit and outdated scans
dependency scanning:
  stage: audit_scan
  tags:
    - ohtu-build-3
  allow_failure: true
  only:
    - schedules
  script:
    # Run npm audit and npm outdated commands and write outputs to a txt file.
    - echo "Running npm diagnostics, audit and outdated..."
    - export RESULT_FILE="./npm_scan_results.txt"
    # Create result file
    - touch $RESULT_FILE
    # Write to the result file
    - echo " ************ ORGREK-FRONTEND NPM AUDIT RESULT ************ " >> $RESULT_FILE
    - echo "https://version.helsinki.fi/tike-ohtu/orgrek-frontend" >> $RESULT_FILE
    - echo "" >> $RESULT_FILE
    - echo "=== npm audit security report ===" >> $RESULT_FILE
    - echo "" >> $RESULT_FILE
    # Run npm audit and "catch" the possible non zero exit code (https://docs.gitlab.com/ee/ci/yaml/#script)
    - 'npm audit  >> $RESULT_FILE || exit_code=$?'
    # npm audit --parseable | awk -F $'\t' 'NF {print "   Package: "$2, "\tLevel: "$3, "\tMore info: "$6}' # this would be nice format
    # Add a message based on npm audit's return code
    - if [ $exit_code -ne 0 ]; then echo "Some vulnerabilities was found, check the above packages." >> $RESULT_FILE; fi;
    - if [ $exit_code -eq 0 ]; then echo "All is good, enjoy the moment." >> $RESULT_FILE; fi;
    - echo "" >> $RESULT_FILE
    - echo " ************ ORGREK-FRONTEND NPM OUTDATED RESULT ************ " >> $RESULT_FILE
    - echo "" >> $RESULT_FILE
    - echo "=== npm outdated report ===" >> $RESULT_FILE
    - echo "" >> $RESULT_FILE
    # Run npm outdated and "catch" the possible non zero exit code (https://docs.gitlab.com/ee/ci/yaml/#script)
    - npm outdated >> $RESULT_FILE || exit_code=$?
    - echo "" >> $RESULT_FILE
    - echo " ************ END OF FILE ************ " >> $RESULT_FILE
    - cat $RESULT_FILE
    - echo "Done with npm diagnostics."
    - echo "Sending results to Slack..."
    # Send result file to "audit-logs" channel in Ohtu's Slack space (see https://api.slack.com/methods/files.upload).
    - "curl -F file=@${CI_PROJECT_DIR}/$RESULT_FILE -F 'initial_comment=Orgrek-frontend npm report' -F channels=${AUDIT_RESULT_SLACK_CHANNEL_ID} -F filename=$RESULT_FILE -F filetype=text -H 'Authorization: Bearer '${SLACK_FILE_UPLOAD_TOKEN} https://slack.com/api/files.upload"
    - echo "Done with sending results to Slack."
