/* eslint-disable max-lines */
export const tree = [
  {
    fi: {
      id: 'a1',
      uniqueId: 42785051,
      name: 'Helsingin yliopisto (HY)',
      hierarchies: ['talous'],
      children: [
        {
          id: '3130',
          uniqueId: 42275629,
          name: 'HY, Rehtorin alaiset erilliset laitokset (ERLA)',
          hierarchies: ['talous'],
          children: [
            {
              id: '3495',
              uniqueId: 31255924,
              name: 'HY, Helsingin yliopiston kirjasto (HULIB)',
              hierarchies: ['talous'],
              children: [],
            },
            {
              id: '6801',
              uniqueId: 75406255,
              name: 'HY, Helsinki Institute of Life Science (HiLIFE)',
              hierarchies: ['talous'],
              children: [
                {
                  id: '3288',
                  uniqueId: 14856367,
                  name: 'HiLIFE, Biotekniikan instituutti (BI)',
                  hierarchies: ['talous'],
                  children: [
                    {
                      id: '4262',
                      uniqueId: 36317368,
                      name: 'HiLIFE-BI, DNA-laboratorio',
                      hierarchies: ['talous'],
                      children: [],
                    },
                    {
                      id: '4298',
                      uniqueId: 43446906,
                      name: 'HiLIFE-BI, Elektronimikroskopia',
                      hierarchies: ['talous'],
                      children: [],
                    },
                    {
                      id: '2771',
                      uniqueId: 92530881,
                      name: 'HiLIFE-BI, LMU (LMU)',
                      hierarchies: ['talous'],
                      children: [],
                    },
                    {
                      id: '5861',
                      uniqueId: 67898302,
                      name: 'HiLIFE-BI, NMR-laboratorio',
                      hierarchies: ['talous'],
                      children: [],
                    },
                    {
                      id: '6304',
                      uniqueId: 33255992,
                      name: 'HiLIFE-BI, Proteiinikemia',
                      hierarchies: ['talous'],
                      children: [
                        {
                          id: '4131',
                          uniqueId: 63423371,
                          name: 'HiLIFE-BI, Biocentrum Helsinki (BCH)',
                          hierarchies: ['talous'],
                          children: [],
                        },
                      ],
                    },
                    {
                      id: '5203',
                      uniqueId: 60376093,
                      name: 'HiLIFE-BI, Viikin Biokeskus',
                      hierarchies: ['talous'],
                      children: [],
                    },
                  ],
                },
                {
                  id: '313',
                  uniqueId: 78659352,
                  name: 'HiLIFE, Infra (HiLIFE-INFRA)',
                  hierarchies: ['talous'],
                  children: [
                    {
                      id: '3459',
                      uniqueId: 57023347,
                      name: 'HiLIFE-INFRA, Helsingin yliopiston koe-eläinkeskus (KEK)',
                      hierarchies: ['talous'],
                      children: [
                        {
                          id: '1277',
                          uniqueId: 76616611,
                          name: 'HiLIFE-INFRA, KEK F-talo',
                          hierarchies: ['talous'],
                          children: [],
                        },
                        {
                          id: '1302',
                          uniqueId: 66417364,
                          name: 'HiLIFE-INFRA, KEK Meilahti',
                          hierarchies: ['talous'],
                          children: [],
                        },
                        {
                          id: '1291',
                          uniqueId: 18983391,
                          name: 'HiLIFE-INFRA, KEK Muuntogeenit',
                          hierarchies: ['talous'],
                          children: [],
                        },
                        {
                          id: '1266',
                          uniqueId: 10839898,
                          name: 'HiLIFE-INFRA, KEK Suuret eläimet',
                          hierarchies: ['talous'],
                          children: [],
                        },
                      ],
                    },
                  ],
                },
                {
                  id: '6795',
                  uniqueId: 16136825,
                  name: 'HiLIFE, Joint Activities (HiLIFE-JOINT)',
                  hierarchies: ['talous'],
                  children: [
                    {
                      id: '325',
                      uniqueId: 92984422,
                      name: 'HiLIFE-JOINT, Common',
                      hierarchies: ['talous'],
                      children: [],
                    },
                    {
                      id: '319',
                      uniqueId: 15242172,
                      name: 'HiLIFE-JOINT, Tenure Track',
                      hierarchies: ['talous'],
                      children: [],
                    },
                  ],
                },
                {
                  id: '3245',
                  uniqueId: 19005470,
                  name: 'HiLIFE, Neurotieteen tutkimuskeskus (NC)',
                  hierarchies: ['talous'],
                  children: [],
                },
                {
                  id: '3211',
                  uniqueId: 62907430,
                  name: 'HiLIFE, Suomen molekyylilääketieteen instituutti (FIMM)',
                  hierarchies: ['talous'],
                  children: [
                    {
                      id: '2500',
                      uniqueId: 53477031,
                      name: 'HiLIFE-FIMM, Biopankki',
                      hierarchies: ['talous'],
                      children: [],
                    },
                    {
                      id: '2492',
                      uniqueId: 96388567,
                      name: 'HiLIFE-FIMM, Teknologiakeskus',
                      hierarchies: ['talous'],
                      children: [
                        {
                          id: '4971',
                          uniqueId: 86326452,
                          name: 'HiLIFE-FIMM, HTB',
                          hierarchies: ['talous'],
                          children: [],
                        },
                        {
                          id: '6666',
                          uniqueId: 38268184,
                          name: 'HiLIFE-FIMM, NGS',
                          hierarchies: ['talous'],
                          children: [],
                        },
                        {
                          id: '6588',
                          uniqueId: 80988194,
                          name: 'HiLIFE-FIMM, Sekvensointiyksikkö',
                          hierarchies: ['talous'],
                          children: [],
                        },
                      ],
                    },
                    {
                      id: '2486',
                      uniqueId: 26224062,
                      name: 'HiLIFE-FIMM, Tutkimusryhmät',
                      hierarchies: ['talous'],
                      children: [
                        {
                          id: '4771',
                          uniqueId: 63147123,
                          name: 'HiLIFE-FIMM, Tutkimusryhmä Aittokallio Tero',
                          hierarchies: ['talous'],
                          children: [],
                        },
                        {
                          id: '6157',
                          uniqueId: 16315347,
                          name: 'HiLIFE-FIMM, Tutkimusryhmä Ganna Andrea',
                          hierarchies: ['talous'],
                          children: [],
                        },
                        {
                          id: '1793',
                          uniqueId: 18117149,
                          name: 'HiLIFE-FIMM, Tutkimusryhmä Kallioniemi Olli',
                          hierarchies: ['talous'],
                          children: [],
                        },
                        {
                          id: '2722',
                          uniqueId: 78228076,
                          name: 'HiLIFE-FIMM, Tutkimusryhmä Lundin Johan',
                          hierarchies: ['talous'],
                          children: [],
                        },
                        {
                          id: '4442',
                          uniqueId: 60945456,
                          name: 'HiLIFE-FIMM, Tutkimusryhmä N.N.03',
                          hierarchies: ['talous'],
                          children: [],
                        },
                        {
                          id: '5132',
                          uniqueId: 73400147,
                          name: 'HiLIFE-FIMM, Tutkimusryhmä N.N.06',
                          hierarchies: ['talous'],
                          children: [],
                        },
                        {
                          id: '6148',
                          uniqueId: 47086829,
                          name: 'HiLIFE-FIMM, Tutkimusryhmä Palotie Aarno',
                          hierarchies: ['talous'],
                          children: [],
                        },
                        {
                          id: '1802',
                          uniqueId: 11904901,
                          name: 'HiLIFE-FIMM, Tutkimusryhmä Pitkänen Esa',
                          hierarchies: ['talous'],
                          children: [],
                        },
                        {
                          id: '6475',
                          uniqueId: 70361465,
                          name: 'HiLIFE-FIMM, Tutkimusryhmä Ripatti Samuli',
                          hierarchies: ['talous'],
                          children: [],
                        },
                        {
                          id: '6558',
                          uniqueId: 88283714,
                          name: 'HiLIFE-FIMM, Tutkimusryhmä Saarela Janna',
                          hierarchies: ['talous'],
                          children: [],
                        },
                        {
                          id: '5163',
                          uniqueId: 85029197,
                          name: 'HiLIFE-FIMM, Tutkimusryhmä Verschuren Emmy',
                          hierarchies: ['talous'],
                          children: [],
                        },
                      ],
                    },
                  ],
                },
              ],
            },
            {
              id: '3483',
              uniqueId: 22323245,
              name: 'HY, Kansalliskirjasto (KK)',
              hierarchies: ['talous'],
              children: [
                {
                  id: '1403',
                  uniqueId: 74736279,
                  name: 'KK, Kirjastoverkkopalvelut',
                  hierarchies: ['talous'],
                  children: [],
                },
                {
                  id: '4917',
                  uniqueId: 72357966,
                  name: 'KK, Tutkimuskirjasto',
                  hierarchies: ['talous'],
                  children: [],
                },
                {
                  id: '2262',
                  uniqueId: 63571285,
                  name: 'KK, Yhteiset',
                  hierarchies: ['talous'],
                  children: [],
                },
              ],
            },
            {
              id: '3388',
              uniqueId: 94853296,
              name: 'HY, Kielikeskus (KIELIKESKUS)',
              hierarchies: ['talous'],
              children: [
                {
                  id: '1441',
                  uniqueId: 73928526,
                  name: 'Kielikeskus, Kielipalvelut',
                  hierarchies: ['talous'],
                  children: [],
                },
              ],
            },
            {
              id: '3356',
              uniqueId: 44486451,
              name: 'HY, Luonnontieteellinen keskusmuseo (LUOMUS)',
              hierarchies: ['talous'],
              children: [
                {
                  id: '5408',
                  uniqueId: 10140198,
                  name: 'LUOMUS, Biodiversiteetti-informatiikan yksikkö',
                  hierarchies: ['talous'],
                  children: [],
                },
                {
                  id: '4390',
                  uniqueId: 46238290,
                  name: 'LUOMUS, Eläintieteen yksikkö',
                  hierarchies: ['talous'],
                  children: [],
                },
                {
                  id: '1583',
                  uniqueId: 24924193,
                  name: 'LUOMUS, Kasvitieteen yksikkö',
                  hierarchies: ['talous'],
                  children: [],
                },
                {
                  id: '3956',
                  uniqueId: 52297249,
                  name: 'LUOMUS, Luonnontieteiden yksikkö',
                  hierarchies: ['talous'],
                  children: [],
                },
              ],
            },
            {
              id: '3411',
              uniqueId: 43311374,
              name: 'HY, Tietotekniikkakeskus (TIKE)',
              hierarchies: ['talous'],
              children: [
                {
                  id: '2908',
                  uniqueId: 27321600,
                  name: 'TIKE, Asiakaspalvelut (ASPA)',
                  hierarchies: ['talous'],
                  children: [],
                },
                {
                  id: '4726',
                  uniqueId: 59523286,
                  name: 'TIKE, Teknologiapalvelut (TEPA)',
                  hierarchies: ['talous'],
                  children: [],
                },
                {
                  id: '4805',
                  uniqueId: 94298967,
                  name: 'TIKE, Tietohallinto (TIHA)',
                  hierarchies: ['talous'],
                  children: [],
                },
                {
                  id: '4820',
                  uniqueId: 38919588,
                  name: 'TIKE, Tietotekniikkaratkaisut (TIRA)',
                  hierarchies: ['talous'],
                  children: [],
                },
                {
                  id: '5283',
                  uniqueId: 59457884,
                  name: 'TIKE, Yhteiset',
                  hierarchies: ['talous'],
                  children: [],
                },
              ],
            },
            {
              id: '3167',
              uniqueId: 20492220,
              name: 'HY, Tutkijakollegium (HCAS)',
              hierarchies: ['talous'],
              children: [],
            },
            {
              id: '3423',
              uniqueId: 61567238,
              name: 'HY, UniSport (UNISPORT)',
              hierarchies: ['talous'],
              children: [
                {
                  id: '4996',
                  uniqueId: 51140586,
                  name: 'UniSport, Keskusta',
                  hierarchies: ['talous'],
                  children: [],
                },
                {
                  id: '5002',
                  uniqueId: 95888394,
                  name: 'UniSport, Kumpula',
                  hierarchies: ['talous'],
                  children: [],
                },
                {
                  id: '5008',
                  uniqueId: 51961924,
                  name: 'UniSport, Meilahti',
                  hierarchies: ['talous'],
                  children: [],
                },
                {
                  id: '5014',
                  uniqueId: 80412647,
                  name: 'UniSport, Otaniemi',
                  hierarchies: ['talous'],
                  children: [],
                },
                {
                  id: '5020',
                  uniqueId: 49428042,
                  name: 'UniSport, Töölö',
                  hierarchies: ['talous'],
                  children: [],
                },
                {
                  id: '5026',
                  uniqueId: 37496285,
                  name: 'UniSport, Viikki',
                  hierarchies: ['talous'],
                  children: [],
                },
              ],
            },
          ],
        },
        {
          id: '6770',
          uniqueId: 32800844,
          name: 'HY, Tiedekunnat (TDK)',
          hierarchies: ['talous'],
          children: [
            {
              id: '3278',
              uniqueId: 90111204,
              name: 'HY, Bio- ja ympäristötieteellinen tiedekunta (BYTDK)',
              hierarchies: ['talous'],
              children: [
                {
                  id: '4070',
                  uniqueId: 62570520,
                  name: 'BYTDK, Biologiset asemat (BYTDK-ASEMAT)',
                  hierarchies: ['talous'],
                  children: [
                    {
                      id: '3016',
                      uniqueId: 92025297,
                      name: 'BYTDK-ASEMAT, Kilpisjärven biologinen asema',
                      hierarchies: ['talous'],
                      children: [],
                    },
                    {
                      id: '3039',
                      uniqueId: 80058917,
                      name: 'BYTDK-ASEMAT, Lammin biologinen asema',
                      hierarchies: ['talous'],
                      children: [],
                    },
                    {
                      id: '3530',
                      uniqueId: 11146774,
                      name: 'BYTDK-ASEMAT, Tvärminnen eläintieteellinen asema',
                      hierarchies: ['talous'],
                      children: [],
                    },
                  ],
                },
                {
                  id: '22684',
                  uniqueId: 53272668,
                  name: 'BYTDK, Ekosysteemit ja ympäristö -tutkimusohjelma (ECOENV)',
                  hierarchies: ['talous'],
                  children: [
                    {
                      id: '23426',
                      uniqueId: 27574252,
                      name: 'BYTDK-ECOENV, Täydentävä rahoitus',
                      hierarchies: ['talous'],
                      children: [
                        {
                          id: '3962',
                          uniqueId: 28947407,
                          name: 'BYTDK-ECOENV, Akvaattiset tieteet',
                          hierarchies: ['talous'],
                          children: [],
                        },
                        {
                          id: '5514',
                          uniqueId: 17516847,
                          name: 'BYTDK-ECOENV, Ympäristöekologia',
                          hierarchies: ['talous'],
                          children: [],
                        },
                        {
                          id: '5531',
                          uniqueId: 14314602,
                          name: 'BYTDK-ECOENV, Ympäristömuutos ja -politiikka',
                          hierarchies: ['talous'],
                          children: [],
                        },
                        {
                          id: '3110',
                          uniqueId: 36942913,
                          name: 'BYTDK-ECOENV, Ympäristötieteet',
                          hierarchies: ['talous'],
                          children: [],
                        },
                      ],
                    },
                  ],
                },
                {
                  id: '22667',
                  uniqueId: 30232763,
                  name: 'BYTDK, Molekulaaristen ja integratiivisten biotieteiden tutkimusohjelma (MIBS)',
                  hierarchies: ['talous'],
                  children: [
                    {
                      id: '23433',
                      uniqueId: 43513740,
                      name: 'BYTDK-MIBS, Täydentävä rahoitus',
                      hierarchies: ['talous'],
                      children: [
                        {
                          id: '3636',
                          uniqueId: 49038649,
                          name: 'BYTDK-MIBS, Biotieteet',
                          hierarchies: ['talous'],
                          children: [],
                        },
                        {
                          id: '2089',
                          uniqueId: 62582922,
                          name: 'BYTDK-MIBS, Hermofysiologian laboratorio',
                          hierarchies: ['talous'],
                          children: [],
                        },
                        {
                          id: '6201',
                          uniqueId: 40775229,
                          name: 'BYTDK-MIBS, Perinnöllisyystiede',
                          hierarchies: ['talous'],
                          children: [],
                        },
                        {
                          id: '5386',
                          uniqueId: 34633888,
                          name: 'BYTDK-MIBS, Yleinen mikrobiologia',
                          hierarchies: ['talous'],
                          children: [],
                        },
                      ],
                    },
                  ],
                },
                {
                  id: '22700',
                  uniqueId: 42618602,
                  name: 'BYTDK, Organismi- ja evoluutiobiologian tutkimusohjelma (OEB)',
                  hierarchies: ['talous'],
                  children: [
                    {
                      id: '23448',
                      uniqueId: 65278720,
                      name: 'BYTDK-OEB, Täydentävä rahoitus',
                      hierarchies: ['talous'],
                      children: [
                        {
                          id: '1635',
                          uniqueId: 25891390,
                          name: 'BYTDK-OEB, Kasvibiologia',
                          hierarchies: ['talous'],
                          children: [],
                        },
                      ],
                    },
                  ],
                },
                {
                  id: '4122',
                  uniqueId: 46923832,
                  name: 'BYTDK, Tiedekunnan yhteiset (BYTDK-YHT)',
                  hierarchies: ['talous'],
                  children: [
                    {
                      id: '2098',
                      uniqueId: 39916187,
                      name: 'BYTDK, Kestävyystieteen instituutti (HELSUS)',
                      hierarchies: ['talous'],
                      children: [],
                    },
                  ],
                },
              ],
            },
            {
              id: '4380',
              uniqueId: 77061680,
              name: 'HY, Eläinlääketieteellinen tiedekunta (ELTDK)',
              hierarchies: ['talous'],
              children: [
                {
                  id: '3300',
                  uniqueId: 50793169,
                  name: 'ELTDK, Tiedekunnan osastot (ELTDK-OSASTOT)',
                  hierarchies: ['talous'],
                  children: [
                    {
                      id: '4319',
                      uniqueId: 52755188,
                      name: 'ELTDK, Elintarvikehygienian ja ympäristöterveyden osasto (EHYT)',
                      hierarchies: ['talous'],
                      children: [],
                    },
                    {
                      id: '4369',
                      uniqueId: 31598459,
                      name: 'ELTDK, Eläinlääketieteellisten biotieteiden osasto (EBIO)',
                      hierarchies: ['talous'],
                      children: [],
                    },
                    {
                      id: '1330',
                      uniqueId: 13769841,
                      name: 'ELTDK, Kliinisen hevos- ja pieneläinlääketieteen osasto (KHPO)',
                      hierarchies: ['talous'],
                      children: [],
                    },
                    {
                      id: '1313',
                      uniqueId: 92581048,
                      name: 'ELTDK, Kliinisen tuotantoeläinlääketieteen osasto (KTO)',
                      hierarchies: ['talous'],
                      children: [],
                    },
                    {
                      id: '4354',
                      uniqueId: 26757420,
                      name: 'ELTDK, Tiedekunnan yhteiset',
                      hierarchies: ['talous'],
                      children: [],
                    },
                  ],
                },
                {
                  id: '3588',
                  uniqueId: 53344738,
                  name: 'ELTDK, Yliopistollinen eläinsairaala (YES)',
                  hierarchies: ['talous'],
                  children: [
                    {
                      id: '4228',
                      uniqueId: 72720720,
                      name: 'ELTDK-YES, Diagnostinen kuvantaminen (DGKUV)',
                      hierarchies: ['talous'],
                      children: [],
                    },
                    {
                      id: '4396',
                      uniqueId: 79839502,
                      name: 'ELTDK-YES, Hallinto',
                      hierarchies: ['talous'],
                      children: [],
                    },
                    {
                      id: '2077',
                      uniqueId: 31018629,
                      name: 'ELTDK-YES, Hevossairaala (HES)',
                      hierarchies: ['talous'],
                      children: [],
                    },
                    {
                      id: '229',
                      uniqueId: 61963552,
                      name: 'ELTDK-YES, Laboratorioyksikkö (YESLAB)',
                      hierarchies: ['talous'],
                      children: [],
                    },
                    {
                      id: '6218',
                      uniqueId: 65364769,
                      name: 'ELTDK-YES, Pieneläinsairaala (PES)',
                      hierarchies: ['talous'],
                      children: [],
                    },
                    {
                      id: '4880',
                      uniqueId: 54393624,
                      name: 'ELTDK-YES, Tuotantoeläinsairaala (TES)',
                      hierarchies: ['talous'],
                      children: [],
                    },
                  ],
                },
              ],
            },
            {
              id: '3309',
              uniqueId: 60350723,
              name: 'HY, Farmasian tiedekunta (FTDK)',
              hierarchies: ['talous'],
              children: [
                {
                  id: '2530',
                  uniqueId: 98208194,
                  name: 'FTDK, Farmasian tiedekunta (FTDK)',
                  hierarchies: ['talous'],
                  children: [
                    {
                      id: '7191',
                      uniqueId: 15938286,
                      name: 'FTDK, Farmakologian ja lääkehoidon osasto',
                      hierarchies: ['talous'],
                      children: [],
                    },
                    {
                      id: '7202',
                      uniqueId: 37005791,
                      name: 'FTDK, Farmaseuttisten biotieteiden osasto',
                      hierarchies: ['talous'],
                      children: [],
                    },
                    {
                      id: '7180',
                      uniqueId: 41627559,
                      name: 'FTDK, NO_NAME_fi',
                      hierarchies: ['talous'],
                      children: [],
                    },
                  ],
                },
              ],
            },
            {
              id: '3327',
              uniqueId: 93158555,
              name: 'HY, Humanistinen tiedekunta (HUMTDK)',
              hierarchies: ['talous'],
              children: [
                {
                  id: '3267',
                  uniqueId: 90594786,
                  name: 'HUMTDK, Aleksanteri-instituutti (AI)',
                  hierarchies: ['talous'],
                  children: [],
                },
                {
                  id: '22675',
                  uniqueId: 99433319,
                  name: 'HUMTDK, Digitaalisten ihmistieteiden osasto (DIGIHUM)',
                  hierarchies: ['talous'],
                  children: [],
                },
                {
                  id: '22634',
                  uniqueId: 15140363,
                  name: 'HUMTDK, Filosofian, historian ja taiteiden tutkimuksen osasto (FHT)',
                  hierarchies: ['talous'],
                  children: [
                    {
                      id: '2992',
                      uniqueId: 27854436,
                      name: 'HUMTDK, Filosofian, historian, kulttuurin ja taiteiden tutkimuksen laitos 2010-2017 (X-FHKT)',
                      hierarchies: ['talous'],
                      children: [],
                    },
                  ],
                },
                {
                  id: '22625',
                  uniqueId: 53602392,
                  name: 'HUMTDK, Kielten osasto (KIELET)',
                  hierarchies: ['talous'],
                  children: [
                    {
                      id: '3005',
                      uniqueId: 66590616,
                      name: 'HUMTDK, Nykykielten laitos 2010-2017 (X-NYKYKIELET)',
                      hierarchies: ['talous'],
                      children: [],
                    },
                  ],
                },
                {
                  id: '22708',
                  uniqueId: 74723689,
                  name: 'HUMTDK, Kulttuurien osasto (KULT)',
                  hierarchies: ['talous'],
                  children: [
                    {
                      id: '3654',
                      uniqueId: 54899735,
                      name: 'HUMTDK, Maailman kulttuurien laitos 2010-2017 (X-MAKULA)',
                      hierarchies: ['talous'],
                      children: [],
                    },
                  ],
                },
                {
                  id: '2923',
                  uniqueId: 87336130,
                  name: 'HUMTDK, Suomalais-ugrilainen ja pohjoismainen osasto (SUP)',
                  hierarchies: ['talous'],
                  children: [
                    {
                      id: '22692',
                      uniqueId: 24217025,
                      name: 'HUMTDK, Suomen kielen, suomalais-ugrilaisten ja pohjoismaisten kielten ja kirjallisuuksien laitos 2010-2017 (X-NORSU)',
                      hierarchies: ['talous'],
                      children: [],
                    },
                  ],
                },
                {
                  id: '2029',
                  uniqueId: 79955254,
                  name: 'HUMTDK, Tiedekunnan yhteiset (HUMTDK-YHT)',
                  hierarchies: ['talous'],
                  children: [],
                },
              ],
            },
            {
              id: '3346',
              uniqueId: 56332909,
              name: 'HY, Kasvatustieteellinen tiedekunta (KTDK)',
              hierarchies: ['talous'],
              children: [
                {
                  id: '331',
                  uniqueId: 63148521,
                  name: 'KTDK, Kasvatustieteiden osasto (KASVO)',
                  hierarchies: ['talous'],
                  children: [
                    {
                      id: '3600',
                      uniqueId: 31712110,
                      name: 'KTDK, Käyttäytymistieteet',
                      hierarchies: ['talous'],
                      children: [],
                    },
                    {
                      id: '3062',
                      uniqueId: 43640005,
                      name: 'KTDK, Opettajankoulutus',
                      hierarchies: ['talous'],
                      children: [],
                    },
                  ],
                },
                {
                  id: '2196',
                  uniqueId: 22129432,
                  name: 'KTDK, NO_NAME_fi (KTDK-KOULUT)',
                  hierarchies: ['talous'],
                  children: [
                    {
                      id: '26935',
                      uniqueId: 46856790,
                      name: 'KTDK-KOULUT, Helsingin normaalilyseo alakoulu',
                      hierarchies: ['talous'],
                      children: [],
                    },
                    {
                      id: '2143',
                      uniqueId: 52605282,
                      name: 'KTDK-KOULUT, Helsingin normaalilyseo yläkoulu ja lukio',
                      hierarchies: ['talous'],
                      children: [],
                    },
                    {
                      id: '5217',
                      uniqueId: 77212464,
                      name: 'KTDK-KOULUT, Viikin normaalikoulu alakoulu',
                      hierarchies: ['talous'],
                      children: [],
                    },
                    {
                      id: '5228',
                      uniqueId: 72610015,
                      name: 'KTDK-KOULUT, Viikin normaalikoulu yläkoulu ja lukio',
                      hierarchies: ['talous'],
                      children: [],
                    },
                  ],
                },
                {
                  id: '2899',
                  uniqueId: 24063456,
                  name: 'KTDK, NO_NAME_fi (KTDK-YHT)',
                  hierarchies: ['talous'],
                  children: [],
                },
              ],
            },
            {
              id: '3368',
              uniqueId: 16549737,
              name: 'HY, Lääketieteellinen tiedekunta (LTDK)',
              hierarchies: ['talous'],
              children: [
                {
                  id: '939',
                  uniqueId: 17515586,
                  name: 'LTDK, Clinicum (CLINICUM)',
                  hierarchies: ['talous'],
                  children: [
                    {
                      id: '4239',
                      uniqueId: 47611622,
                      name: 'LTDK-CLINICUM, Diagnostis-terapeuttinen osasto',
                      hierarchies: ['talous'],
                      children: [],
                    },
                    {
                      id: '1987',
                      uniqueId: 60079453,
                      name: 'LTDK-CLINICUM, Ihotautien, allergologian ja sukupuolitautien klinikka',
                      hierarchies: ['talous'],
                      children: [],
                    },
                    {
                      id: '7074',
                      uniqueId: 87266622,
                      name: 'LTDK-CLINICUM, Johtaja ja yhteiset',
                      hierarchies: ['talous'],
                      children: [],
                    },
                    {
                      id: '970',
                      uniqueId: 89454894,
                      name: 'LTDK-CLINICUM, Kansanterveystieteen osasto',
                      hierarchies: ['talous'],
                      children: [],
                    },
                    {
                      id: '1373',
                      uniqueId: 19523138,
                      name: 'LTDK-CLINICUM, Kirurgian osasto',
                      hierarchies: ['talous'],
                      children: [],
                    },
                    {
                      id: '2804',
                      uniqueId: 16922770,
                      name: 'LTDK-CLINICUM, Lastenklinikka',
                      hierarchies: ['talous'],
                      children: [],
                    },
                    {
                      id: '5815',
                      uniqueId: 75797391,
                      name: 'LTDK-CLINICUM, Naistenklinikka',
                      hierarchies: ['talous'],
                      children: [],
                    },
                    {
                      id: '5844',
                      uniqueId: 76941234,
                      name: 'LTDK-CLINICUM, Neurotieteiden osasto',
                      hierarchies: ['talous'],
                      children: [],
                    },
                    {
                      id: '6310',
                      uniqueId: 50303115,
                      name: 'LTDK-CLINICUM, Psykiatrian osasto',
                      hierarchies: ['talous'],
                      children: [],
                    },
                    {
                      id: '6603',
                      uniqueId: 52119439,
                      name: 'LTDK-CLINICUM, Silmä- ja korvaklinikka',
                      hierarchies: ['talous'],
                      children: [],
                    },
                    {
                      id: '6628',
                      uniqueId: 92213262,
                      name: 'LTDK-CLINICUM, Sisätautien osasto',
                      hierarchies: ['talous'],
                      children: [],
                    },
                    {
                      id: '7054',
                      uniqueId: 60795484,
                      name: 'LTDK-CLINICUM, Suu- ja leukasairauksien osasto',
                      hierarchies: ['talous'],
                      children: [],
                    },
                    {
                      id: '4655',
                      uniqueId: 56066258,
                      name: 'LTDK-CLINICUM, Syöpätautien osasto',
                      hierarchies: ['talous'],
                      children: [],
                    },
                    {
                      id: '5436',
                      uniqueId: 29481084,
                      name: 'LTDK-CLINICUM, Yleislääketieteen ja perusterveydenhuollon osasto',
                      hierarchies: ['talous'],
                      children: [],
                    },
                  ],
                },
                {
                  id: '955',
                  uniqueId: 81552327,
                  name: 'LTDK, Medicum (MEDICUM)',
                  hierarchies: ['talous'],
                  children: [
                    {
                      id: '4015',
                      uniqueId: 29350874,
                      name: 'LTDK-MEDICUM, Anatomian osasto',
                      hierarchies: ['talous'],
                      children: [],
                    },
                    {
                      id: '4099',
                      uniqueId: 98640542,
                      name: 'LTDK-MEDICUM, Bakteriologian ja immunologian osasto',
                      hierarchies: ['talous'],
                      children: [],
                    },
                    {
                      id: '4171',
                      uniqueId: 58741539,
                      name: 'LTDK-MEDICUM, Biokemian ja kehitysbiologian osasto',
                      hierarchies: ['talous'],
                      children: [],
                    },
                    {
                      id: '2590',
                      uniqueId: 81216927,
                      name: 'LTDK-MEDICUM, Farmakologian osasto',
                      hierarchies: ['talous'],
                      children: [],
                    },
                    {
                      id: '2390',
                      uniqueId: 59072997,
                      name: 'LTDK-MEDICUM, Fysiologian osasto',
                      hierarchies: ['talous'],
                      children: [],
                    },
                    {
                      id: '1847',
                      uniqueId: 64467699,
                      name: 'LTDK-MEDICUM, Johtaja ja yhteiset',
                      hierarchies: ['talous'],
                      children: [],
                    },
                    {
                      id: '1353',
                      uniqueId: 74963998,
                      name: 'LTDK-MEDICUM, Kliinisen farmakologian osasto',
                      hierarchies: ['talous'],
                      children: [],
                    },
                    {
                      id: '946',
                      uniqueId: 60515472,
                      name: 'LTDK-MEDICUM, Kliinisen kemian ja hematologian osasto',
                      hierarchies: ['talous'],
                      children: [],
                    },
                    {
                      id: '3666',
                      uniqueId: 59161008,
                      name: 'LTDK-MEDICUM, Lääketieteellisen genetiikan ja perinnöllisyyslääketieteen osasto',
                      hierarchies: ['talous'],
                      children: [],
                    },
                    {
                      id: '962',
                      uniqueId: 29910513,
                      name: 'LTDK-MEDICUM, Oikeuslääketieteen osasto',
                      hierarchies: ['talous'],
                      children: [],
                    },
                    {
                      id: '6183',
                      uniqueId: 68294104,
                      name: 'LTDK-MEDICUM, Patologian osasto',
                      hierarchies: ['talous'],
                      children: [],
                    },
                    {
                      id: '6789',
                      uniqueId: 94998996,
                      name: 'LTDK-MEDICUM, Psykologian ja logopedian osasto',
                      hierarchies: ['talous'],
                      children: [],
                    },
                    {
                      id: '7064',
                      uniqueId: 55917472,
                      name: 'LTDK-MEDICUM, Tukipalveluyksiköt',
                      hierarchies: ['talous'],
                      children: [],
                    },
                    {
                      id: '5257',
                      uniqueId: 36018731,
                      name: 'LTDK-MEDICUM, Virologian osasto',
                      hierarchies: ['talous'],
                      children: [],
                    },
                  ],
                },
                {
                  id: '3677',
                  uniqueId: 79809964,
                  name: 'LTDK, Tiedekunnan yhteiset (LTDK-YHT)',
                  hierarchies: ['talous'],
                  children: [],
                },
                {
                  id: '3612',
                  uniqueId: 93034081,
                  name: 'LTDK, Tutkimusohjelmayksikkö (RPU)',
                  hierarchies: ['talous'],
                  children: [
                    {
                      id: '2356',
                      uniqueId: 23002098,
                      name: 'LTDK-RPU, Applied Tumor Genomics (ATG)',
                      hierarchies: ['talous'],
                      children: [
                        {
                          id: '2347',
                          uniqueId: 52551365,
                          name: 'LTDK-RPU, Genomitiedon hyödyntämisen huippuyksikkö (Aaltonen Lauri)',
                          hierarchies: ['talous'],
                          children: [],
                        },
                        {
                          id: '2154',
                          uniqueId: 51236296,
                          name: 'LTDK-RPU, Helsingin biolääketieteellinen tutkijakoulu (HBGS)',
                          hierarchies: ['talous'],
                          children: [],
                        },
                      ],
                    },
                    {
                      id: '26616',
                      uniqueId: 69604245,
                      name: 'LTDK-RPU, Human Microbiome Research',
                      hierarchies: ['talous'],
                      children: [],
                    },
                    {
                      id: '26640',
                      uniqueId: 48724836,
                      name: 'LTDK-RPU, Individualized Drug Therapy (INDIVIDRUG)',
                      hierarchies: ['talous'],
                      children: [],
                    },
                    {
                      id: '1876',
                      uniqueId: 82567865,
                      name: 'LTDK-RPU, Johtaja ja yhteiset',
                      hierarchies: ['talous'],
                      children: [
                        {
                          id: '7087',
                          uniqueId: 83759600,
                          name: 'LTDK-RPU, Johtajan laboratorio',
                          hierarchies: ['talous'],
                          children: [],
                        },
                      ],
                    },
                    {
                      id: '1471',
                      uniqueId: 30286927,
                      name: 'LTDK-RPU, Keskitetyt teknologiapalvelut',
                      hierarchies: ['talous'],
                      children: [],
                    },
                    {
                      id: '26590',
                      uniqueId: 29173590,
                      name: 'LTDK-RPU, Research Program Systems Oncology (ONCOSYS)',
                      hierarchies: ['talous'],
                      children: [],
                    },
                    {
                      id: '4219',
                      uniqueId: 89627971,
                      name: 'LTDK-RPU, Research Program for Clinical and Molecular Metabolism (CAMM)',
                      hierarchies: ['talous'],
                      children: [],
                    },
                    {
                      id: '26564',
                      uniqueId: 95093111,
                      name: 'LTDK-RPU, Sleep and stress in health and in transition from acute to chronic diseases (SLEEPWELL)',
                      hierarchies: ['talous'],
                      children: [],
                    },
                    {
                      id: '5753',
                      uniqueId: 74686668,
                      name: 'LTDK-RPU, Stem Cells and Metabolism Research Program (STEMM)',
                      hierarchies: ['talous'],
                      children: [
                        {
                          id: '2461',
                          uniqueId: 25179703,
                          name: 'LTDK-RPU, FinMIT huippuyksikkö (Wartiovaara Anu)',
                          hierarchies: ['talous'],
                          children: [],
                        },
                      ],
                    },
                    {
                      id: '5725',
                      uniqueId: 45617392,
                      name: 'LTDK-RPU, Translational Cancer Medicine Program (CAN-PRO)',
                      hierarchies: ['talous'],
                      children: [
                        {
                          id: '4666',
                          uniqueId: 79847635,
                          name: 'LTDK-RPU, Syövän biologian huippuyksikkö (Alitalo Kari)',
                          hierarchies: ['talous'],
                          children: [],
                        },
                      ],
                    },
                    {
                      id: '1946',
                      uniqueId: 64390273,
                      name: 'LTDK-RPU, Translational Immunology Research Program (TRIMM)',
                      hierarchies: ['talous'],
                      children: [],
                    },
                    {
                      id: '4871',
                      uniqueId: 36590169,
                      name: 'LTDK-RPU, Tukipalvelut',
                      hierarchies: ['talous'],
                      children: [],
                    },
                  ],
                },
              ],
            },
            {
              id: '3378',
              uniqueId: 51987233,
              name: 'HY, Maatalous-metsätieteellinen tiedekunta (MMTDK)',
              hierarchies: ['talous'],
              children: [
                {
                  id: '3541',
                  uniqueId: 64692425,
                  name: 'MMTDK, Elintarvike- ja ravitsemustieteiden osasto (FAN)',
                  hierarchies: ['talous'],
                  children: [
                    {
                      id: '23441',
                      uniqueId: 19926103,
                      name: 'MMTDK-FAN, Täydentävä rahoitus',
                      hierarchies: ['talous'],
                      children: [],
                    },
                  ],
                },
                {
                  id: '277',
                  uniqueId: 54032432,
                  name: 'MMTDK, Infra (INFRA)',
                  hierarchies: ['talous'],
                  children: [
                    {
                      id: '2007',
                      uniqueId: 61962952,
                      name: 'MMTDK-INFRA, Hyytiälän metsäasema',
                      hierarchies: ['talous'],
                      children: [],
                    },
                    {
                      id: '23469',
                      uniqueId: 87903887,
                      name: 'MMTDK-INFRA, Laitekeskus ja kasvihuone',
                      hierarchies: ['talous'],
                      children: [],
                    },
                    {
                      id: '5239',
                      uniqueId: 79816361,
                      name: 'MMTDK-INFRA, Viikin opetus- ja tutkimustila',
                      hierarchies: ['talous'],
                      children: [],
                    },
                  ],
                },
                {
                  id: '3074',
                  uniqueId: 29040353,
                  name: 'MMTDK, Maataloustieteiden osasto (MAAT)',
                  hierarchies: ['talous'],
                  children: [
                    {
                      id: '265',
                      uniqueId: 96550474,
                      name: 'MMTDK-MAAT, Täydentävä rahoitus',
                      hierarchies: ['talous'],
                      children: [],
                    },
                  ],
                },
                {
                  id: '3098',
                  uniqueId: 77275048,
                  name: 'MMTDK, Metsätieteiden osasto (METSA)',
                  hierarchies: ['talous'],
                  children: [
                    {
                      id: '271',
                      uniqueId: 45263215,
                      name: 'MMTDK-METSA, Täydentävä rahoitus',
                      hierarchies: ['talous'],
                      children: [],
                    },
                  ],
                },
                {
                  id: '22658',
                  uniqueId: 47971657,
                  name: 'MMTDK, Mikrobiologian osasto (MIKRO)',
                  hierarchies: ['talous'],
                  children: [
                    {
                      id: '23462',
                      uniqueId: 43084831,
                      name: 'MMTDK-MIKRO, Täydentävä rahoitus',
                      hierarchies: ['talous'],
                      children: [],
                    },
                  ],
                },
                {
                  id: '3223',
                  uniqueId: 62536910,
                  name: 'MMTDK, Ruralia-instituutti (RURALIA)',
                  hierarchies: ['talous'],
                  children: [
                    {
                      id: '6528',
                      uniqueId: 21786401,
                      name: 'MMTDK-RURALIA, Mikkeli',
                      hierarchies: ['talous'],
                      children: [],
                    },
                    {
                      id: '6540',
                      uniqueId: 59001836,
                      name: 'MMTDK-RURALIA, Seinäjoki',
                      hierarchies: ['talous'],
                      children: [],
                    },
                  ],
                },
                {
                  id: '3086',
                  uniqueId: 42163482,
                  name: 'MMTDK, Taloustieteen osasto (TAL)',
                  hierarchies: ['talous'],
                  children: [
                    {
                      id: '23455',
                      uniqueId: 21602735,
                      name: 'MMTDK-TAL, Täydentävä rahoitus',
                      hierarchies: ['talous'],
                      children: [],
                    },
                  ],
                },
                {
                  id: '3788',
                  uniqueId: 52586605,
                  name: 'MMTDK, Tiedekunnan yhteiset (MMTDK-YHT)',
                  hierarchies: ['talous'],
                  children: [],
                },
              ],
            },
            {
              id: '3257',
              uniqueId: 99185517,
              name: 'HY, Matemaattis-luonnontieteellinen tiedekunta (MLTDK)',
              hierarchies: ['talous'],
              children: [
                {
                  id: '3576',
                  uniqueId: 16075073,
                  name: 'MLTDK, Fysiikan osasto (PHYS)',
                  hierarchies: ['talous'],
                  children: [
                    {
                      id: '7213',
                      uniqueId: 69246922,
                      name: 'MLTDK-PHYS, Alkeishiukkasfysiikka (testi)',
                      hierarchies: ['talous'],
                      children: [],
                    },
                    {
                      id: '3863',
                      uniqueId: 35206230,
                      name: 'MLTDK-PHYS, Materiaalifysiikka',
                      hierarchies: ['talous'],
                      children: [],
                    },
                  ],
                },
                {
                  id: '3435',
                  uniqueId: 68863986,
                  name: 'MLTDK, Fysiikan tutkimuslaitos (HIP)',
                  hierarchies: ['talous'],
                  children: [],
                },
                {
                  id: '2959',
                  uniqueId: 28280286,
                  name: 'MLTDK, Geotieteiden ja maantieteen osasto (GEO)',
                  hierarchies: ['talous'],
                  children: [
                    {
                      id: '6855',
                      uniqueId: 59310964,
                      name: 'MLTDK-GEO, Kaupunkimaantieteen ja aluetutkimuksen osasto',
                      hierarchies: ['talous'],
                      children: [],
                    },
                    {
                      id: '6861',
                      uniqueId: 45237680,
                      name: 'MLTDK-GEO, Osasto',
                      hierarchies: ['talous'],
                      children: [],
                    },
                    {
                      id: '6579',
                      uniqueId: 69994070,
                      name: 'MLTDK-GEO, Seismologian instituutti',
                      hierarchies: ['talous'],
                      children: [],
                    },
                  ],
                },
                {
                  id: '22434',
                  uniqueId: 11008466,
                  name: 'MLTDK, Ilmakehätieteiden keskus (INAR)',
                  hierarchies: ['talous'],
                  children: [
                    {
                      id: '1955',
                      uniqueId: 18244634,
                      name: 'testi no. 2, Osasto',
                      hierarchies: ['talous'],
                      children: [],
                    },
                  ],
                },
                {
                  id: '3050',
                  uniqueId: 56849599,
                  name: 'MLTDK, Kemian osasto (CHEM)',
                  hierarchies: ['talous'],
                  children: [
                    {
                      id: '5952',
                      uniqueId: 36405438,
                      name: 'MLTDK-CHEM, Opettajankoulutus',
                      hierarchies: ['talous'],
                      children: [],
                    },
                    {
                      id: '6887',
                      uniqueId: 24263197,
                      name: 'MLTDK-CHEM, Osasto',
                      hierarchies: ['talous'],
                      children: [],
                    },
                    {
                      id: '6404',
                      uniqueId: 96239777,
                      name: 'MLTDK-CHEM, Radiokemia',
                      hierarchies: ['talous'],
                      children: [],
                    },
                    {
                      id: '6867',
                      uniqueId: 75598231,
                      name: 'MLTDK-CHEM, Synteesi ja analyysi',
                      hierarchies: ['talous'],
                      children: [],
                    },
                    {
                      id: '1508',
                      uniqueId: 44796991,
                      name: 'MLTDK-CHEM, VERIFIN (VERIFIN)',
                      hierarchies: ['talous'],
                      children: [],
                    },
                  ],
                },
                {
                  id: '3027',
                  uniqueId: 86567106,
                  name: 'MLTDK, Matematiikan ja tilastotieteen osasto (MATHSTAT)',
                  hierarchies: ['talous'],
                  children: [
                    {
                      id: '22643',
                      uniqueId: 19886449,
                      name: 'MLTDK-MATHSTAT, Osasto',
                      hierarchies: ['talous'],
                      children: [],
                    },
                  ],
                },
                {
                  id: '3854',
                  uniqueId: 77538749,
                  name: 'MLTDK, Tiedekunnan yhteiset (MLTDK-YHT)',
                  hierarchies: ['talous'],
                  children: [
                    {
                      id: '2731',
                      uniqueId: 79390273,
                      name: 'MLTDK, Helsingin yliopiston LUMA-tiedekasvatuskeskus',
                      hierarchies: ['talous'],
                      children: [],
                    },
                    {
                      id: '7041',
                      uniqueId: 34109941,
                      name: 'MLTDK, LUMA-keskus Suomi',
                      hierarchies: ['talous'],
                      children: [],
                    },
                  ],
                },
                {
                  id: '2979',
                  uniqueId: 20899458,
                  name: 'MLTDK, Tietojenkäsittelytieteen osasto (CS)',
                  hierarchies: ['talous'],
                  children: [
                    {
                      id: '22611',
                      uniqueId: 46195472,
                      name: 'MLTDK-CS, Osasto',
                      hierarchies: ['talous'],
                      children: [],
                    },
                  ],
                },
              ],
            },
            {
              id: '5935',
              uniqueId: 10020336,
              name: 'HY, Oikeustieteellinen tiedekunta (OIKTDK)',
              hierarchies: ['talous'],
              children: [
                {
                  id: '3236',
                  uniqueId: 22963335,
                  name: 'OIKTDK, NO_NAME_fi (OIKTDK)',
                  hierarchies: ['talous'],
                  children: [
                    {
                      id: '5919',
                      uniqueId: 55134536,
                      name: 'OIKTDK, Oikeustieteellinen koulutus, Vaasa',
                      hierarchies: ['talous'],
                      children: [],
                    },
                  ],
                },
              ],
            },
            {
              id: '3201',
              uniqueId: 55437194,
              name: 'HY, Svenska social- och kommunalhögskolan (SSKH-testi)',
              hierarchies: ['talous'],
              children: [
                {
                  id: '4607',
                  uniqueId: 14898342,
                  name: 'SSKH, Svenska social- och kommunalhögskolan (SSKH)',
                  hierarchies: ['talous'],
                  children: [
                    {
                      id: '1829',
                      uniqueId: 24424047,
                      name: 'SSKH, Journalistik och mediekunskap',
                      hierarchies: ['talous'],
                      children: [],
                    },
                    {
                      id: '6549',
                      uniqueId: 89766327,
                      name: 'SSKH, Rättsvetenskap',
                      hierarchies: ['talous'],
                      children: [],
                    },
                    {
                      id: '6639',
                      uniqueId: 90768497,
                      name: 'SSKH, Socialpsykologi och psykologi',
                      hierarchies: ['talous'],
                      children: [],
                    },
                    {
                      id: '6648',
                      uniqueId: 91487546,
                      name: 'SSKH, Socialt arbete och socialpolitik',
                      hierarchies: ['talous'],
                      children: [],
                    },
                    {
                      id: '6657',
                      uniqueId: 83176257,
                      name: 'SSKH, Sociologi',
                      hierarchies: ['talous'],
                      children: [],
                    },
                    {
                      id: '4502',
                      uniqueId: 41550547,
                      name: 'SSKH, Statskunskap med förvaltning',
                      hierarchies: ['talous'],
                      children: [],
                    },
                  ],
                },
              ],
            },
            {
              id: '3191',
              uniqueId: 98306098,
              name: 'HY, Teologinen tiedekunta (TTDK)',
              hierarchies: ['talous'],
              children: [
                {
                  id: '4741',
                  uniqueId: 25599761,
                  name: 'TTDK, Teologinen tiedekunta (TTDK)',
                  hierarchies: ['talous'],
                  children: [
                    {
                      id: '4287',
                      uniqueId: 66818968,
                      name: 'TTDK, Eksegetiikka',
                      hierarchies: ['talous'],
                      children: [],
                    },
                    {
                      id: '1392',
                      uniqueId: 53048544,
                      name: 'TTDK, Kirkkohistoria',
                      hierarchies: ['talous'],
                      children: [],
                    },
                    {
                      id: '2871',
                      uniqueId: 73503045,
                      name: 'TTDK, Käytännöllinen teologia',
                      hierarchies: ['talous'],
                      children: [],
                    },
                    {
                      id: '4644',
                      uniqueId: 83326215,
                      name: 'TTDK, Systemaattinen teologia',
                      hierarchies: ['talous'],
                      children: [],
                    },
                    {
                      id: '2225',
                      uniqueId: 70392143,
                      name: 'TTDK, Tiedekunnan yhteiset',
                      hierarchies: ['talous'],
                      children: [],
                    },
                    {
                      id: '5063',
                      uniqueId: 41686077,
                      name: 'TTDK, Uskontotiede',
                      hierarchies: ['talous'],
                      children: [],
                    },
                  ],
                },
              ],
            },
            {
              id: '3157',
              uniqueId: 20155246,
              name: 'HY, Valtiotieteellinen tiedekunta (VALTTDK)',
              hierarchies: ['talous'],
              children: [
                {
                  id: '5104',
                  uniqueId: 99452087,
                  name: 'VALTTDK, Tiedekunnan yhteiset (VALTTDK-YHT)',
                  hierarchies: ['talous'],
                  children: [],
                },
                {
                  id: '22618',
                  uniqueId: 36734044,
                  name: 'VALTTDK, Tieteenalat',
                  hierarchies: ['talous'],
                  children: [
                    {
                      id: '1529',
                      uniqueId: 91183618,
                      name: 'VALTTDK, Globaali kehitystutkimus',
                      hierarchies: ['talous'],
                      children: [],
                    },
                    {
                      id: '2882',
                      uniqueId: 27531873,
                      name: 'VALTTDK, Käytännöllinen filosofia',
                      hierarchies: ['talous'],
                      children: [],
                    },
                    {
                      id: '6266',
                      uniqueId: 79336899,
                      name: 'VALTTDK, Poliittinen historia',
                      hierarchies: ['talous'],
                      children: [],
                    },
                    {
                      id: '2947',
                      uniqueId: 80126021,
                      name: 'VALTTDK, Politiikan ja talouden tutkimuksen laitos (POLTAL)',
                      hierarchies: ['talous'],
                      children: [],
                    },
                    {
                      id: '6675',
                      uniqueId: 61036507,
                      name: 'VALTTDK, Sosiaali- ja kulttuuriantropologia',
                      hierarchies: ['talous'],
                      children: [],
                    },
                    {
                      id: '6694',
                      uniqueId: 52314480,
                      name: 'VALTTDK, Sosiaalipsykologia',
                      hierarchies: ['talous'],
                      children: [],
                    },
                    {
                      id: '6705',
                      uniqueId: 42025960,
                      name: 'VALTTDK, Sosiaalityö',
                      hierarchies: ['talous'],
                      children: [],
                    },
                    {
                      id: '6716',
                      uniqueId: 40132841,
                      name: 'VALTTDK, Sosiologia',
                      hierarchies: ['talous'],
                      children: [
                        {
                          id: '22838',
                          uniqueId: 99694647,
                          name: 'VALTTDK, CEACG-yksikkö (CEACG)',
                          hierarchies: ['talous'],
                          children: [],
                        },
                        {
                          id: '22846',
                          uniqueId: 18243047,
                          name: 'VALTTDK, Väestötiede',
                          hierarchies: ['talous'],
                          children: [],
                        },
                      ],
                    },
                    {
                      id: '4682',
                      uniqueId: 81681922,
                      name: 'VALTTDK, Talous- ja sosiaalihistoria',
                      hierarchies: ['talous'],
                      children: [],
                    },
                    {
                      id: '4701',
                      uniqueId: 92861515,
                      name: 'VALTTDK, Taloustiede',
                      hierarchies: ['talous'],
                      children: [],
                    },
                    {
                      id: '5172',
                      uniqueId: 28427739,
                      name: 'VALTTDK, Viestintä',
                      hierarchies: ['talous'],
                      children: [],
                    },
                    {
                      id: '5309',
                      uniqueId: 90678703,
                      name: 'VALTTDK, Yhteiskuntapolitiikka',
                      hierarchies: ['talous'],
                      children: [],
                    },
                    {
                      id: '5086',
                      uniqueId: 55881534,
                      name: 'VALTTDK, Yleinen valtio-oppi',
                      hierarchies: ['talous'],
                      children: [],
                    },
                  ],
                },
                {
                  id: '22650',
                  uniqueId: 10880982,
                  name: 'VALTTDK, Tutkimusyksiköt',
                  hierarchies: ['talous'],
                  children: [
                    {
                      id: '2610',
                      uniqueId: 91358394,
                      name: 'VALTTDK, Eurooppa-tutkimuksen keskus (CES)',
                      hierarchies: ['talous'],
                      children: [],
                    },
                    {
                      id: '6940',
                      uniqueId: 80286061,
                      name: 'VALTTDK, Kriminologian ja oikeuspolitiikan instituutti (KRIMO)',
                      hierarchies: ['talous'],
                      children: [],
                    },
                    {
                      id: '6929',
                      uniqueId: 11130088,
                      name: 'VALTTDK, Kuluttajatutkimuskeskus (KTK)',
                      hierarchies: ['talous'],
                      children: [],
                    },
                    {
                      id: '4839',
                      uniqueId: 62060775,
                      name: 'VALTTDK, Yhteiskuntadatatieteen keskus (CSDS)',
                      hierarchies: ['talous'],
                      children: [],
                    },
                  ],
                },
              ],
            },
          ],
        },
        {
          id: '743',
          uniqueId: 54806742,
          name: 'HY, Tutkijakoulutus (DSDP)',
          hierarchies: ['talous'],
          children: [
            {
              id: '217',
              uniqueId: 67823548,
              name: 'HY, Helsingin yliopiston tutkijakoulu (UHDS)',
              hierarchies: ['talous'],
              children: [],
            },
          ],
        },
        {
          id: '840',
          uniqueId: 46582376,
          name: 'HY, Yhteinen toiminta (YHT)',
          hierarchies: ['talous'],
          children: [
            {
              id: '26913',
              uniqueId: 88551185,
              name: 'HY, Yliopiston johto ja yhteiset (HY-YHT)',
              hierarchies: ['talous'],
              children: [
                {
                  id: '22597',
                  uniqueId: 11102370,
                  name: 'HY, Yhteiset tilat (HY-YHTTILAT)',
                  hierarchies: ['talous'],
                  children: [
                    {
                      id: '4093',
                      uniqueId: 42305850,
                      name: 'HY-YHTTILAT, Asunto- ja majoituspalvelut',
                      hierarchies: ['talous'],
                      children: [],
                    },
                    {
                      id: '5508',
                      uniqueId: 16433467,
                      name: 'HY-YHTTILAT, Toimitilat',
                      hierarchies: ['talous'],
                      children: [],
                    },
                    {
                      id: '5500',
                      uniqueId: 75421743,
                      name: 'HY-YHTTILAT, Vapaat tilat',
                      hierarchies: ['talous'],
                      children: [],
                    },
                  ],
                },
                {
                  id: '5481',
                  uniqueId: 10254527,
                  name: 'HY, Yliopiston johto (HY-JOHTO)',
                  hierarchies: ['talous'],
                  children: [
                    {
                      id: '7097',
                      uniqueId: 10916572,
                      name: 'HY-JOHTO, Yliopiston yhteiset',
                      hierarchies: ['talous'],
                      children: [],
                    },
                  ],
                },
                {
                  id: '1460',
                  uniqueId: 13674022,
                  name: 'HY, Yliopiston yhteiset varat (HY-YHTVARAT)',
                  hierarchies: ['talous'],
                  children: [
                    {
                      id: '1891',
                      uniqueId: 22433398,
                      name: 'HY-YHTVARAT, Rahoitus',
                      hierarchies: ['talous'],
                      children: [],
                    },
                  ],
                },
              ],
            },
            {
              id: '3140',
              uniqueId: 77096679,
              name: 'HY, Yliopistopalvelut (YPA)',
              hierarchies: ['talous'],
              children: [
                {
                  id: '2130',
                  uniqueId: 36044908,
                  name: 'YPA, Henkilöstöpalvelut (HR)',
                  hierarchies: ['talous'],
                  children: [],
                },
                {
                  id: '5963',
                  uniqueId: 20571691,
                  name: 'YPA, Opetus- ja opiskelijapalvelut (OPA)',
                  hierarchies: ['talous'],
                  children: [
                    {
                      id: '6034',
                      uniqueId: 66711126,
                      name: 'YPA-OPA, Neuvontapalvelut ja liikkuvuuspalvelut',
                      hierarchies: ['talous'],
                      children: [],
                    },
                  ],
                },
                {
                  id: '4462',
                  uniqueId: 95511199,
                  name: 'YPA, Talouspalvelut (TALOUS)',
                  hierarchies: ['talous'],
                  children: [],
                },
                {
                  id: '3399',
                  uniqueId: 81813101,
                  name: 'YPA, Tilat ja kiinteistöt (TILA)',
                  hierarchies: ['talous'],
                  children: [],
                },
                {
                  id: '4576',
                  uniqueId: 38288498,
                  name: 'YPA, Toiminnanohjausyksikkö (TOIMI)',
                  hierarchies: ['talous'],
                  children: [
                    {
                      id: '2699',
                      uniqueId: 34747286,
                      name: 'YPA-TOIMI, Lahden yliopistokeskuksen koordinaatioyksikkö (LYK)',
                      hierarchies: ['talous'],
                      children: [],
                    },
                  ],
                },
                {
                  id: '4892',
                  uniqueId: 81645305,
                  name: 'YPA, Tutkimuspalvelut (TUTTO)',
                  hierarchies: ['talous'],
                  children: [],
                },
                {
                  id: '5190',
                  uniqueId: 37998196,
                  name: 'YPA, Viestintä ja yhteiskuntasuhteet (VYS)',
                  hierarchies: ['talous'],
                  children: [],
                },
                {
                  id: '2249',
                  uniqueId: 64002635,
                  name: 'YPA, Yhteiset (YPA-YHT)',
                  hierarchies: ['talous'],
                  children: [],
                },
                {
                  id: '5417',
                  uniqueId: 95814475,
                  name: 'YPA, Yleishallinto (YLHA)',
                  hierarchies: ['talous'],
                  children: [],
                },
              ],
            },
          ],
        },
        {
          id: '6777',
          uniqueId: 74223428,
          name: 'Muut yksiköt (MUUT)',
          hierarchies: ['talous'],
          children: [
            {
              id: '3471',
              uniqueId: 21682135,
              name: 'MUUT, HY+ (HYPLUS)',
              hierarchies: ['talous'],
              children: [],
            },
            {
              id: '28654',
              uniqueId: 69640366,
              name: 'MUUT, Helsingin yliopistokiinteistöt Oy (HYK)',
              hierarchies: ['talous'],
              children: [
                {
                  id: '28690',
                  uniqueId: 28686730,
                  name: 'HYK, HY:n käyttö',
                  hierarchies: ['talous'],
                  children: [],
                },
                {
                  id: '28674',
                  uniqueId: 77438361,
                  name: 'HYK, Hallinto',
                  hierarchies: ['talous'],
                  children: [],
                },
                {
                  id: '28706',
                  uniqueId: 99369402,
                  name: 'HYK, Muu käyttö / monikäyttö',
                  hierarchies: ['talous'],
                  children: [],
                },
              ],
            },
            {
              id: '283',
              uniqueId: 68909643,
              name: 'MUUT, Helsingin yliopiston kiinteistöpalvelut Oy (HY247)',
              hierarchies: ['talous'],
              children: [
                {
                  id: '27010',
                  uniqueId: 44895547,
                  name: 'HY247, Rakennuttamispalvelut',
                  hierarchies: ['talous'],
                  children: [],
                },
                {
                  id: '23091',
                  uniqueId: 94718814,
                  name: 'HY247, Toimitila- ja käyttäjäpalvelut',
                  hierarchies: ['talous'],
                  children: [],
                },
                {
                  id: '23096',
                  uniqueId: 49992784,
                  name: 'HY247, Valmentamo',
                  hierarchies: ['talous'],
                  children: [],
                },
                {
                  id: '23101',
                  uniqueId: 40965119,
                  name: 'HY247, Ylläpitopalvelut',
                  hierarchies: ['talous'],
                  children: [],
                },
              ],
            },
            {
              id: '2018',
              uniqueId: 83231586,
              name: 'MUUT, Helsingin yliopiston rahastot (HYR)',
              hierarchies: ['talous'],
              children: [
                {
                  id: '6960',
                  uniqueId: 24701832,
                  name: 'HYR, Rahastot',
                  hierarchies: ['talous'],
                  children: [],
                },
              ],
            },
            {
              id: '247',
              uniqueId: 46436786,
              name: 'MUUT, Konsernin pienet kiinteistöyhtiöt (K000)',
              hierarchies: ['talous'],
              children: [],
            },
            {
              id: '3507',
              uniqueId: 94314457,
              name: 'MUUT, Tuntematon yksikkö/ tekninen korjaus (XXXX)',
              hierarchies: ['talous'],
              children: [],
            },
          ],
        },
      ],
    },
    sv: {
      id: 'a1',
      uniqueId: 42785051,
      name: 'Helsingfors universitet (HY)',
      hierarchies: ['talous'],
      children: [],
    },
    en: {
      id: 'a1',
      uniqueId: 42785051,
      name: 'University of Helsinki (HY)',
      hierarchies: ['talous'],
      children: [],
    },
  },
];
