#!/bin/sh
. "$(dirname "$0")/_/husky.sh"
# reformat code
npx lint-staged

# add missing translations to every translation file
# key is found in one -> should be found in others.

# set removeUnusedKeys to true and debug to true in i18next-scanner.config.js
# to remove unusedkeys and see what is going to be removed
# you can run this manually without commit by (note that reformatting is also executed):
# git hook run pre-commit
npx i18next-scanner --config i18next-scanner.config.js
